spring.application.name=ManytoOne

spring.datasource.username=root
spring.datasource.password=Ravis04@
spring.datasource.url=jdbc:mysql://localhost:3306/RaghuSpring


spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true