spring.application.name=03App

#properties

com.app.code=1234
com.app.name=Ravi
com.app.status=true
com.app.names=ravi,shankar,derangula
com.app.info.m1=Hui
com.app.info.m2=helo
com.app.info.m3=bye



com.app.prop.s-id=101
com.app.prop.s-name=Shankar
